language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
  - rust: stable
    script: cargo test --verbose
  - rust: beta
    script:
      - cargo test --verbose
      - cargo test --verbose --features 'pin'
  - rust: nightly
    script:
      - cargo test --verbose
      - cargo test --verbose --features 'pin'
      - cargo test --verbose --features 'nightly'
